document/urls.py
from django.conf.urls import url

from . import views


app_name = "document"
urlpatterns = [
    url(r"^list", views.documents_list, name="list"),
]

pei/urls.py
from django.conf.urls import url
from .views import PeiHome

app_name = 'pei'
urlpatterns = [
    url(r'^$', PeiHome.as_view(), name="home"),
]

user/urls.py
from django.conf.urls import url

from . import views

app_name = 'user'
urlpatterns = [
    url(r'^profil/$', views.profile_view,
        name='profile'),
    url(r'^profil/edition/$', views.profile_edit_view,
        name='profile.edit'),
    url(r'^profil/(?P<username>\w+)/$', views.profile_view,
        name='profile.show'),
]

shared/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Language(models.Model):
    name = models.CharField(
        _("nom"),
        max_length=255,
    )

    class Meta:
        verbose_name = _("langue")
        verbose_name_plural = _("langues")

    def __str__(self):
        return self.name


class Subject(models.Model):
    name = models.CharField(
        _("nom"),
        max_length=255,
    )

    class Meta:
        verbose_name = _("discipline")
        verbose_name_plural = _("disciplines")

    def __str__(self):
        return self.name

shared/templates/shared/base-simple.html
{% extends "shared/base.html" %}

{% block real_content %}
<main class="col-sm-12">
    {% block content %}{% endblock %}
</main>
{% endblock %}

shared/templates/shared/base.html
{% load i18n staticfiles %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>
       {% block title %}{% endblock %} - GestioPEI
  </title>

  {# Fonts #}
  <link href="{% static "fonts/glyphicons-halflings-regular.ttf" %}">
  <link href="https://fonts.googleapis.com/css?family=Dosis|Saira+Semi+Condensed|Saira:600|Work+Sans" rel="stylesheet">

  {# Global stylesheets #}
  <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
  <link href="{% static "css/global.css" %}" rel="stylesheet">

  {% block extra_css %}
      {# Override this in templates to add extra stylesheets #}
  {% endblock %}
</head>

<body>

  <header>
    {% include "shared/base_header.html" %}
  </header>

  <div id="principal">
    <div class="container">

      {% if messages %}
      <div class="row">
        {% for message in messages %}
        <div class="alert message-{{ message.tags }} alter-dismissible fade in" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="{% trans "Close" %}">
            <span aria-hidden="true">×</span>
          </button>
          <strong>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.DEBUG %}{% trans "DEBUG" %}&#8239;:
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}{% trans "Info"%}&#8239;:
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}{% trans "Succès"%}&#8239;:
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}{% trans "Attention" %}&#8239;:
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}{% trans "Erreur" %}&#8239;:
            {% endif %}
          </strong>
          {{ message }}
        </div>
        {% endfor %}
      </div>
      {% endif %}

      <div class="row">
        {% block real_content %}
        <main class="col-sm-8">
          {% block content %}{% endblock %}
        </main>
        <aside class="col-sm-4">
          {{ message_title }}
          {% block aside %}{% endblock %}
        </aside>
        {% endblock %}
      </div>

    </div><!-- /.container -->
  </div><!-- /#principal -->

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
  {# Global javascript #}
  <script src="{% static "js/jquery-3.2.1.min.js" %}" type="text/javascript"></script>
  <script src="{% static "js/bootstrap.min.js" %}" type="text/javascript"></script>

  {% block extra_js %}
    {# Override this in templates to add extra javascript #}
  {% endblock %}
</body>

</html>

shared/templates/shared/base_header.html
{% load i18n %}

<div class="strong-banner">
  <div class="container">
    <nav class="navbar navbar-inverse">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-menu">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url "pei:home" %}">GestioPEI</a>
      </div>
      <div class="collapse navbar-collapse" id="main-menu">
        <ul class="nav navbar-nav">
          {% if user.is_authenticated %}
            {% if not user.is_volunteer or user.volunteer.approved %}
              <li><a href="{% url "document:list" %}">{% trans "Documents utiles" %}</a></li>
            {% endif %}
            <li><a href="{% url "user:profile" %}">{% trans "Mon profil" %}</a></li>
            {% if user.is_staff %}
            <li><a href="{% url "admin:index" %}">{% trans "Admin" %}</a></li>
            {% endif %}
            <li><a href="{% url "account_logout" %}">{% trans "Déconnexion" %}</a></li>
          {% else %}
            <li><a href="{% url "account_signup" %}">{% trans "Inscription (bénévoles)" %}</a></li>
            <li><a href="{% url "account_login" %}">{% trans "Connexion" %}</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </div><!-- /.container -->
</div><!-- /.strong-banner -->

shared/templates/shared/calendar.html
{% if html %}
  <div class="calendar">
    {{ html }}
  </div>
{% elif user.is_staff or user.is_superuser %}
  <p class="text-warning">
    Le calendrier n'est pas affiché car il n'est pas paramétré. Vous pouvez le
    configurer depuis
    <a href="{% url "admin:dynamic_preferences_globalpreferencemodel_changelist" %}">
    l'administration</a> (option "<tt>calendar_id</tt>").
  </p>
{% endif %}