pei/urls.py
from django.conf.urls import url
from .views import PeiHome

app_name = 'pei'
urlpatterns = [
    url(r'^$', PeiHome.as_view(), name="home"),
]

user/urls.py
from django.conf.urls import url

from . import views

app_name = 'user'
urlpatterns = [
    url(r'^profil/$', views.profile_view,
        name='profile'),
    url(r'^profil/edition/$', views.profile_edit_view,
        name='profile.edit'),
    url(r'^profil/(?P<username>\w+)/$', views.profile_view,
        name='profile.show'),
]

user/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models
from django.db.models import Q
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse

class User(AbstractUser):
    phone = models.CharField(
        _('numéro de téléphone'),
        max_length=20,
        blank=True,
    )
    birthdate = models.DateField(
        _('date de naissance'),
        blank=True, null=True,
    )
    address = models.TextField(
        _('adresse postale'),
        blank=True,
    )

    objects = UserManager()

    class Meta:
        verbose_name = _("utilisateur")
        verbose_name_plural = _("utilisateurs")
        ordering = ('last_name', 'first_name')

    def __str__(self):
        return self.get_full_name() or self.username

    # The three following properties are shortcuts to determine user's type and
    # provide abstraction of data layer.

    @property
    def is_gueststudent(self):
        return hasattr(self, 'gueststudent')

    @property
    def is_tutor(self):
        return hasattr(self, 'tutor')

    @property
    def is_volunteer(self):
        return hasattr(self, 'volunteer')

    def specific(self):
        if self.is_gueststudent:
            return self.gueststudent
        if self.is_tutor:
            return self.tutor
        if self.is_volunteer:
            return self.volunteer
        return self

    def get_pei_relationship(self, target):
        if self.is_superuser:
            return "admin"
        if self == target:
            return "self"
        elif target.is_gueststudent:
            if self.is_volunteer:
                if target.gueststudent.binome == self.volunteer:
                    return "binome"
                elif target.gueststudent.tandem == self.volunteer:
                    return "tandem"
            elif self.is_tutor:
                if target.gueststudent.tutor == self.tutor:
                    return "tutor" # TODO tuteur oui ?
        elif target.is_volunteer:
            if self.is_gueststudent:
                if self.gueststudent.binome == target.volunteer:
                    return "binome"
                elif self.gueststudent.tandem == target.volunteer:
                    return "tandem"
        return None

    def get_absolute_url(self):
        return reverse("user:profile.show", kwargs={"username":self.username})

class GuestStudent(User):
    ADMINISTRATIVE_STATUS = (
        ('DA', _("demandeur d'asile")),
        ('RS', _("réfugié statutaire")),
        ('PS', _("protection subsidiaire")),
        ('AP', _("apatride")),
        ('A', _("autre")),
    )
    HEALTHCARE_STATUS = (
        ('CMU', _("couverture médicale universelle")),
        ('AME', _("aide médicale d'état")),
        ('NONE', _("aucune aide aux soins")),
    )
    TRANSPORT = (
        ('FREE', _("pass navigo gratuit")),
        ('FS', _("forfait solidarité")),
        ('NORMAL', _("forfait à 73€/mois")),
        ('NONE', _("pas de forfait")),
    )
    FRENCH_LEVEL = (
        ('A1', "A1"),
        ('A2', "A2"),
        ('B1', "B1"),
        ('B2', "B2"),
    )
    CARD_STATUS = (
        ('ND', _("non demandée")),
        ('DC', _("demande en cours")),
        ('R', _("reçue mais non distribuée")),
        ('D', _("distribuée")),
    )
    TICKET_STATUS = (
        ('ND', _("non demandés")),
        ('DC', _("demande en cours")),
        ('R', _("reçus mais non distribués")),
        ('D', _("distribués")),
    )
    subjects = models.ManyToManyField(
        'shared.Subject',
        verbose_name=_("disciplines"),
    )
    home_country = models.CharField(
        _("pays d'origine"),
        max_length=255,
        blank=True,
    )
    administrative_status = models.CharField(
        _("statut administratif"),
        max_length=255,
        choices=ADMINISTRATIVE_STATUS,
        blank=True,
    )
    healthcare_status = models.CharField(
        _("prise en charge médicale"),
        max_length=255,
        choices=HEALTHCARE_STATUS,
        blank=True,
    )
    card_status = models.CharField(
        _("Carte ENS"),
        max_length=255,
        choices=CARD_STATUS,
        blank=True,
    )
    meal_ticket_status = models.CharField(
        _("tickets restaurant"),
        max_length=255,
        choices=TICKET_STATUS,
        blank=True,
    )
    transport = models.CharField(
        _("forfait de transport"),
        max_length=255,
        choices=TRANSPORT,
        blank=True,
    )
    staff_remarks = models.TextField(
        _("remarques de l'équipe"),
        blank=True,
    )
    public_remarks = models.TextField(
        _("remarques publiques"),
        blank=True,
        help_text=_("remarques de l'étudiant·e visibles par le binôme"),
    )
    private_remarks = models.TextField(
        _("remarques privées"),
        blank=True,
        help_text=_("remarques de l'étudiant·e visibles uniquement par "
                    "les administrat·rices·eurs"),
    )
    committee_wishes = models.ManyToManyField(
        'Committee',
        verbose_name=_("comités souhaités"),
        blank=True,
    )
    french_level = models.CharField(
        _("niveau de français"),
        max_length=255,
        choices=FRENCH_LEVEL,
        blank=True,
    )
    tuteur = models.ForeignKey(
        'Tutor',
        verbose_name=_("tuteur"),
        blank=True, null=True,
    )
    tandem = models.ForeignKey(
        'Volunteer',
        verbose_name=_("tandem"),
        related_name='tandem',
        blank=True, null=True,
    )
    binome = models.ForeignKey(
        'Volunteer',
        verbose_name=_("binome"),
        related_name='binome',
        blank=True, null=True,
    )
    languages = models.ManyToManyField(
        'shared.Language',
        verbose_name=_("langues parlées"),
    )

    # This manager is required to make this model correctly works, e.g. with
    # 'ModelForm's.
    objects = UserManager()

    class Meta:
        verbose_name = _("étudiant invité")
        verbose_name_plural = _("étudiants invités")


class VolunteerQuerySet(models.QuerySet):
    def binome_of(self, gueststudents=None, exclude=False):
        """
        Only keep Volunteers who are 'binome' of 'gueststudents' argument.

        If 'gueststudents' is not given, keep Volunteers who are 'binome' of
        any guest student.

        If 'exclude' argument is True, it skip these Volunteers. Its default
        value is False.
        """
        return self.of_gueststudents(
            positions=['binome'],
            gueststudents=gueststudents, exclude=exclude,
        )

    def tandem_of(self, gueststudents=None, exclude=False):
        """
        Only keep Volunteers who are 'tandem' of 'gueststudents' argument.

        If 'gueststudents' is not given, keep Volunteers who are 'tandem' of
        any guest student.

        If 'exclude' argument is True, it skip these Volunteers. Its default
        value is False.
        """
        return self.of_gueststudents(
            positions=['tandem'],
            gueststudents=gueststudents, exclude=exclude,
        )

    def of_gueststudents(self, gueststudents=None, exclude=False,
                         positions=None):
        if positions is None:
            positions = ['binome', 'tandem']

        filters = Q()
        if 'binome' in positions:
            filters |= (
                Q(binome__isnull=False) if gueststudents is None
                else Q(binome__in=gueststudents)
            )
        if 'tandem' in positions:
            filters |= (
                Q(tandem__isnull=False) if gueststudents is None
                else Q(tandem__in=gueststudents)
            )

        if exclude:
            return self.exclude(filters)
        return self.filter(filters).distinct()


# Inheritance from UserManager is required for the Volunteer model to function
# properly, e.g. with 'ModelForm's.

class VolunteerManager(UserManager.from_queryset(VolunteerQuerySet)):
    """
    FYI: Why is it a subclass ?
    https://docs.djangoproject.com/en/1.11/topics/migrations/#model-managers
    """


class Volunteer(User):
    languages = models.ManyToManyField(
        'shared.Language',
        verbose_name=_("langues parlées"),
        related_name='spoken_vol',
        blank=True,
    )
    language_wishes = models.ManyToManyField(
        'shared.Language',
        verbose_name=_("langues souhaitées"),
        related_name='wishes_vol',
        blank=True,
    )
    subjects = models.ManyToManyField(
        'shared.Subject',
        verbose_name=_("disciplines"),
    )
    committee_wishes = models.ManyToManyField(
        'Committee',
        verbose_name=_("comités souhaités"),
        blank=True,
    )
    position_wishes = models.ManyToManyField(
        'Position',
        verbose_name=_("positions souhaitées"),
        blank=True,
    )
    approved = models.BooleanField(
        _("Approuvé·e par les administrat·rice·eur·s"),
        default=False
    )

    objects = VolunteerManager()

    class Meta:
        verbose_name = _("bénévole")
        verbose_name_plural = _("bénévoles")


class Tutor(User):
    subjects = models.ManyToManyField(
        'shared.Subject',
        verbose_name=_("disciplines"),
    )

    # This manager is required to make this model correctly works, e.g. with
    # 'ModelForm's.
    objects = UserManager()

    class Meta:
        verbose_name = _("tuteur")
        verbose_name_plural = _("tuteurs")


class Position(models.Model):
    name = models.CharField(
        _("nom"),
        max_length=255,
    )

    class Meta:
        verbose_name = _("position")
        verbose_name_plural = _("positions")

    def __str__(self):
        return self.name


class Committee(models.Model):
    name = models.CharField(
        _("nom"),
        max_length=255
    )
    description = models.TextField(
        _('description'),
        blank=True,

user/forms.py
from django import forms
from django.urls import reverse
from django.utils.translation import ugettext as _

from .models import GuestStudent, Tutor, User, Volunteer


class GuestStudentForm(forms.ModelForm):
    class Meta:
        model = GuestStudent
        fields = (
            'first_name', 'last_name', 'birthdate', 'home_country',
            'email', 'phone', 'address',
            'administrative_status', 'healthcare_status', 'transport',
            'subjects', 'committee_wishes',
            'public_remarks', 'private_remarks',
        )


class TutorForm(forms.ModelForm):
    class Meta:
        model = Tutor
        fields = ('first_name', 'last_name', 'email', 'subjects')


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class VolunteerForm(forms.ModelForm):
    class Meta:
        model = Volunteer
        fields = (
            'first_name', 'last_name', 'email', 'phone',
            'subjects', 'languages',
            'language_wishes', 'committee_wishes', 'position_wishes',
        )


class AuthSubUserAdminForm(forms.ModelForm):
    """
    Add an extra help message to the `username` field with a link to change
    the user data related to authentication and authorizations: password,
    permissions, groups memberships, social accounts…

    If instance is being created, only notify user that these changes will be
    available once it is created.

    No Meta class is defined, as it is meant to be used from `ModelAdmin` which
    already manages this.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        pk = self.instance.pk
        if pk is None:
            extra_auth_help = _(
                "Vous aurez la possibilité de modifier les informations "
                "concernant l'accès à ce site une fois l'utilisateur·rice "
                "créé·e."
            )
        else:
            extra_auth_help = _(
                "Suivez <a href=\"{}\" target=\"_blank\">ce lien</a> pour "
                "afficher et modifier les informations concernant l'accès à "
                "ce site de cet·te utilisateur·rice."
                .format(reverse('admin:user_user_change', args=(pk,)))
            )

        if self.fields['username'].help_text:
            self.fields['username'].help_text += '<br>' + extra_auth_help
        else:
            self.fields['username'].help_text += extra_auth_help

user/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views.generic import TemplateView, DetailView
from django.views.generic.edit import FormView

from .forms import GuestStudentForm, TutorForm, UserForm, VolunteerForm
from .models import User

class ProfileView(LoginRequiredMixin, DetailView):
    model = User

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.relationship = self.request.user.get_pei_relationship(self.object)
        if self.relationship is None or self.relationship == "tutor":
            return self.handle_no_permission()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)
    
    def get_object(self):
        if self.kwargs.get('username'):
            return get_object_or_404(User, username=self.kwargs.get('username'))
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)
        context['user_object'] = context['object']
        context['object'] = context['object'].specific()
        context['relationship'] = self.relationship
        return context
        
    def get_template_names(self):
        if self.object.is_volunteer:
            return ['user/profile_volunteer.html']
        elif self.object.is_gueststudent:
            return ['user/profile_gueststudent.html']
        elif self.object.is_tutor:
            return ['user/profile_tutor.html']
        else:
            return ['user/profile.html']

profile_view = ProfileView.as_view()


class ProfileEditView(LoginRequiredMixin, SuccessMessageMixin, FormView):
    """
    Connected user profile edition view.

    Note
        To simplify this view, a user must only be one of the following:
            GuestStudent, Tutor, Volunteer. If this restriction is annoying,
            one should rewrite this view (e.g. with multiple forms).

    """
    template_name = 'user/profile_edit.html'
    success_url = reverse_lazy('user:profile')
    success_message = _("Profil mis à jour.")

    def get_form_class(self):
        user = self.request.user
        if user.is_gueststudent:
            return GuestStudentForm
        elif user.is_tutor:
            return TutorForm
        elif user.is_volunteer:
            return VolunteerForm
        return UserForm

    def get_form_kwargs(self):
        form_kwargs = super().get_form_kwargs()
        user = self.request.user
        if user.is_gueststudent:
            instance = user.gueststudent
        elif user.is_tutor:
            instance = user.tutor
        elif user.is_volunteer:
            instance = user.volunteer
        else:
            instance = user
        form_kwargs['instance'] = instance
        return form_kwargs

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


profile_edit_view = ProfileEditView.as_view()

user/templates/user/profile.html
{% extends "shared/base.html" %}
{% load i18n %}
{% load account socialaccount allauth_ens_social %}

{% block title %}{% trans "Profil de" %} {{ object.get_full_name }}{% endblock %}

{% block real_content %}

<main class="col-sm-{% if request.user == object %}8{% else %}12{% endif %}">
    {% block profile_content %}
    {% endblock %}
</main>

{% if request.user == object %}
<aside class="col-sm-4">
  <h3>{% trans "Gestion" %}</h3>
  <ul>
    <li>
      <a href="{% url "user:profile.edit" %}">{% trans "Éditer mon profil" %}</a>
    </li>
    <li>
      <a href="{% url "account_change_password" %}">{% trans "Mot de passe" %}</a>
    </li>
    {% is_socialaccount_enabled as socialaccount_enabled %}
    {% if socialaccount_enabled %}
    <li>
      <a href="{% url "socialaccount_connections" %}">{% trans "Comptes tiers" %}</a>
    </li>
    {% endif %}
  </ul>
</aside>
{% endif %}

{% endblock %}

user/templates/user/profile_edit.html
{% extends "shared/base.html" %}
{% load i18n crispy_forms_tags %}

{% block title %}{% trans "Mon profil - Édition" %}{% endblock %}

{% block real_content %}

<main class="col-md-6 col-md-offset-3">

<form action="" method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <a href="{% url "user:profile" %}" class="btn btn-default pull-right">
    {% trans "Retour au profil" %}
  </a>
  <button type="submit" class="btn btn-primary">
    {% trans "Enregistrer" %}
  </button>
</form>

</main>

{% endblock %}

user/templates/user/profile_gueststudent.html
{% extends "user/profile.html" %}
{% load i18n %}
{% load account socialaccount allauth_ens_social %}

{% block profile_content %}
    <h1>{{ object.get_full_name }}</h1>
    <p>{% trans "Étudiant⋅e invité⋅e" %}.
        {% if object.binome == request.user.volunteer %}
            {% trans "C'est votre binôme." %}
        {% elif object.tandem == request.user.volunteer %}
            {% trans "C'est votre tandem." %}
        {% elif relationship == "self" %}{% trans "C'est vous !" %}
        {% endif %}
    </p>

        
    <h2>{% trans "Informations personnelles" %}</h2>
    {% if True %}
        {# Toutes les personnes qui ont accès à cette page peuvent voir ces données #}
        <p class="confidentiality">{% trans "Visible par le binôme et le tandem" %}</p>
        {% if object.phone %}<p>{% trans "Téléphone" %} : <a href="tel:{{ object.phone }}">{{ object.phone }}</a></p>{% endif %}
        {% if object.address %}<p>{% trans "Adresse" %} : <span class="address">{{ object.address|linebreaksbr }}</span></p>{% endif %}
        {% if object.birthdate %}<p>{% trans "Date de naissance" %} : {{ object.birthdate|date:"d/m/Y" }}</p>{% endif %}
        {% if object.home_country %}<p>{% trans "Pays d'origine" %} : {{ object.home_country }}</p>{% endif %}
    {% endif %}

    
    <h2>{% trans "Informations d'enseignement" %}</h2>
    {% if True %}
        {# Toutes les personnes qui ont accès à cette page peuvent voir ces données #}
        <p class="confidentiality">{% trans "Visible par le binôme et le tandem" %}</p>
        <p>{% trans "Disciplines" %} : {{ object.subjects.all|join:', ' }}</p>
        <p>{% trans "Langues parlées" %} : {{ object.languages.all|join:', ' }}</p>
        <p>{% trans "Niveau de Français" %} : {{ object.get_french_level_display }}</p>
    {% endif %}

    
    <h2>{% trans "Statut" %}</h2>
    {% if True %}
        {# Toutes les personnes qui ont accès à cette page peuvent voir ces données #}
        <p class="confidentiality">{% trans "Visible par le binôme et le tandem" %}</p>
        <p>{% trans "Statut administratif" %} : {{ object.get_administrative_status_display }}</p>
        <p>{% trans "Prise en charge médicale" %} : {{ object.get_healthcare_status_display }}</p>
    {% endif %}
    
    {% if relationship == "self" or relationship == "admin" %}
        <p class="confidentiality">{% trans "Visible uniquement par les administrat⋅rices⋅eurs" %}</p>
        <p>{% trans "Carte ENS" %} : {{ object.get_card_status_display }}</p>
        <p>{% trans "Tickets restaurants" %} : {{ object.get_meal_ticket_status_display }}</p>
        <p>{% trans "Forfait de transport" %} : {{ object.get_transport_display }}</p>
    {% endif %}

    
    <h2>{% trans "PEI" %}</h2>
    {% if True and object.binome %}
        <h3>{% trans "Binôme" %} : <a href="{{ object.binome.get_absolute_url }}">{{ object.binome.get_full_name }}</a></h3>
        {% if object.binome.phone %}<p>{% trans "Téléphone" %} : <a href="tel:{{ object.binome.phone }}">{{ object.binome.phone }}</a></p>{% endif %}
    {% endif %}

    {% if True and object.tandem %}
        <h3>{% trans "Tandem" %} : <a href="{{ object.tandem.get_absolute_url }}">{{ object.tandem.get_full_name }}</a></h3>
        {% if object.tandem.phone %}<p>{% trans "Téléphone" %} : <a href="tel:{{ object.tandem.phone }}">{{ object.tandem.phone }}</a></p>{% endif %}
    {% endif %}

    {% if relationship == "self" or relationship == "admin" %}{% if object.tutor %}
        <h3>{% trans "Tuteur" %} : <a href="{{ object.tutor.get_absolute_url }}">{{ object.tutor.get_full_name }}</a></h3>
        {% if object.tutor.phone %}<p>{% trans "Téléphone" %} : <a href="tel:{{ object.tutor.phone }}">{{ object.tutor.phone }}</a></p>{% endif %}
    {% endif %}{% endif %}

    
    {% if relationship == "self" or relationship == "admin" %}
        <h3>{% trans "Autres infos" %}</h3>
        <p></p>
    {% endif %}

    
    <h2>{% trans "Remarques" %}</h2>
    {% if True %}
        <h3>{% trans "Remarques de l'équipe" %}</h3>
        <p class="confidentiality">{% trans "Visible par le binôme et le tandem" %}</p>
        <p>{{ object.staff_remarks|linebreaksbr }}</p>
    {% endif %}
    
    {% if True %}
        <h3>{% trans "Remarques publiques de l'étudiant⋅e" %}</h3>
        <p class="confidentiality">{% trans "Visible par le binôme et le tandem" %}</p>
        <p>{{ object.public_remarks|linebreaksbr }}</p>
    {% endif %}
    
    {% if relationship == "self" or relationship == "admin" %}
        <h3>{% trans "Remarques de l'étudiant⋅e" %}</h3>
        <p class="confidentiality">{% trans "Visible uniquement par les administrat⋅rices⋅eurs" %}</p>
        <p>{{ object.private_remarks|linebreaksbr }}</p>
    {% endif %}
{% endblock %}

user/templates/user/profile_tutor.html
{% extends "user/profile.html" %}
{% load i18n %}
{% load account socialaccount allauth_ens_social %}

{% block profile_content %}
    <h1>{{ object.get_full_name }}</h1>
    <p>{% trans "Tuteur" %}. {% if relationship == "tutor" %}{% trans "C'est votre tuteur." %}{% elif relationship == "self" %}{% trans "C'est vous !" %}{% endif %}</p>
    <h2>{% trans "Informations personnelles" %}</h2>
    {% if object.phone %}<p>{% trans "Téléphone" %} : <a href="tel:{{ object.phone }}">{{ object.phone }}</a></p>{% endif %}
{% endblock %}

user/templates/user/profile_volunteer.html
{% extends "user/profile.html" %}
{% load i18n %}
{% load account socialaccount allauth_ens_social %}

{% block profile_content %}
    <h1>{{ object.get_full_name }}</h1>
    <p>{% trans "Bénévole" %}.
        {# Assert : Aucun gueststudent ne sera admin #}
        {% if relationship == "binome" %}
            {% trans "C'est votre binôme." %}
        {% elif relationship == "tandem" %}
            {% trans "C'est votre tandem." %}
        {% elif request.user.volunteer == object %}
            {% trans "C'est vous !" %}
        {% endif %}
    </p>
    <h2>{% trans "Informations personnelles" %}</h2>
    {% if object.phone %}<p>{% trans "Téléphone" %} : <a href="tel:{{ object.phone }}">{{ object.phone }}</a></p>{% endif %}
    
    <h2>{% trans "Langues" %}</h2>
    <p>{% trans "Parlées" %} : {{ object.languages.all|join:', ' }}</p>
    <p>{% trans "Souhaitées" %} : {{ object.language_wishes.all|join:', ' }}</p>

    {% if relationship == "self" or relationship == "admin" %}
        <h2>{% trans "PEI" %}</h2>
        <h3>{% trans "Binôme(s)" %}</h3>
        {% for guest in object.binome.all %}
            <p><a href="{{ guest.get_absolute_url }}">{{ guest.get_full_name }}</a></p>
        {% endfor %}
        <h3>{% trans "Tandem(s)" %}</h3>
        {% for guest in object.tandem.all %}
            <p><a href="{{ guest.get_absolute_url }}">{{ guest.get_full_name }}</a></p>
        {% endfor %}
    {% endif %}
{% endblock %}